---
- hosts: DynamicWeb
  become: true
  gather_facts: false
  tasks:
    - name: base soft
      become: true
      apt:
        name: 
         - apt-transport-https
         - ca-certificates
         - curl
         - software-properties-common
         - mc         
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Add Docker's official GPG key
      become: true
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
      tags:
        - docker

    - name: Verify that we have the key with the fingerprint
      become: true
      apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker

    - name: Set up repository
      become: true
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable"
        state: present
        update_cache: true
      tags:
        - docker

    - name: Update apt packages
      become: true
      apt:
        update_cache: yes
      tags:
        - docker

    - name: Install docker containers
      become: true
      apt:
        name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Add remote user "vagrant" to "docker" group
      become: true
      user:
        name: vagrant
        group: docker
        append: true
      tags:
        - docker

    - name: Copy project
      copy: src=project dest=/home/vagrant

    - name: reset ssh connection
      meta: reset_connection

    - name: Run container
      shell:
        cmd: "docker compose -f docker-compose.yml up -d"
        chdir: /home/vagrant/project
...